### ISSUE TITLE
Don't mandate user and password for source repo

### ISSUE THREAD

**Issue by peternewman** [pkgstore/github-actions-sync#1]
I left these not set in my workflow file and got the following error (where *** would have been the user or password).
`fatal: unable to access 'https://https://example.com/source.git:***@example.com/dest.git': Could not resolve host: https`

I think it just needs a little cotton wool if they're blank or not set or something...

**Comment by uid-meta** [comment]
Hello. This is an old unsupported version. You don't need to use it. Try to find another Action.

**Comment by peternewman** [comment]
> Hello. This is an old unsupported version.

Maybe you should archive the repo and leave a note in the readme and in the marketplace in that case?

> You don't need to use it. Try to find another Action.

Unfortunately I probably do, I'm trying to clone **from** elsewhere to GitHub and most of the other actions are only set up to go the other way, plus it's my preference to run the action from a third repo, which seems to have even less support. It seems to work perfectly well for my task thanks aside from this minor issue.

Does that also mean you wouldn't accept a PR that fixed the issue?

P.S. You can close the issue as not planned or similar, which would be more accurate than "completed".
